export enum Category {
  START_KIT = 'start-kit',
  HTML = 'html',
  CSS = 'css',
  SVG = 'svg',
  DESIGN_TOOLS = 'design-tools',
  GIT = 'git',
  JS = 'js',
  PACKAGE_MANAGERS = 'package-managers',
  CSS_EXTENSIONS = 'css-extensions',
  TYPESCRIPT = 'typescript',
  WEBPACK = 'webpack',
  ANGULAR = 'angular',
  DEV_TOOLS = 'dev-tools',
}
